const doc = (name, detail, required = true) => ({ name, detail, required });

const commonVisaDocs = [
  doc("有效中国普通护照", "原件及资料页扫描；按目的地要求留足有效期和空白页"),
  doc("证件照片", "按官方尺寸、背景和近期拍摄要求准备"),
  doc("行程与住宿", "往返/续程安排、酒店或邀请信息，日期要互相一致"),
  doc("资金与支付能力", "银行流水、收入或资助证明；解释大额进账来源"),
  doc("回国或继续旅行约束", "在职、在读、家庭、资产或下一程证据，按个人情况选择"),
  doc("翻译件", "非目的地官方接受语言的材料，按官方翻译与认证要求准备", false)
];

const commonVisaTips = [
  "先确认访问目的和正确签证类别，再开始填表",
  "所有日期、金额、职业和旅行史必须前后一致",
  "材料齐全不等于获签；不要购买不可退的行程来赌出签"
];

export const applicationGuides = {
  US: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "开始 DS-160 在线申请",
    applicationUrl: "https://ceac.state.gov/genniv/",
    officialGuideLabel: "美国国务院｜Visitor Visa",
    officialGuideUrl: "https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html",
    documentsLabel: "美国国务院｜面谈材料与说明",
    documentsUrl: "https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html",
    processingUrl: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/wait-times.html",
    feeUrl: "https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html",
    requiredDocuments: [doc("护照", "通常需覆盖预计停留期后至少 6 个月"), doc("DS-160 确认页", "每位申请人单独填写并打印确认页"), doc("缴费与预约凭证", "按使领馆指向的预约平台完成"), doc("照片", "按美国签证照片要求准备"), ...commonVisaDocs.slice(3)],
    applicationSteps: ["确认 B2 或 B1/B2 目的", "填写并提交 DS-160", "按使领馆官方指引缴费和预约", "按预约要求面谈并等待通知", "获签后检查签证页；10 年 B 类出发前另查 EVUS"],
    successRate: { status: "official", label: "FY2025 中国籍 B 类调整后拒签率 20.21%（非个人成功率）", url: "https://travel.state.gov/content/dam/visas/Statistics/Non-Immigrant-Statistics/RefusalRates/FY25.pdf", note: "这是国籍维度的统计口径，不能预测个人结果。" },
    riskTips: ["美国国务院统计的是 B 类调整后拒签率，不是“通过率”", "面谈回答要能解释临时访问目的、资金来源和回国约束", "行政审查和护照返还时间不能压缩进出发前最后几天"],
    lastVerified: "2026-08-13"
  },
  GB: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "进入 GOV.UK 在线申请",
    applicationUrl: "https://www.gov.uk/standard-visitor/apply-standard-visitor-visa",
    officialGuideLabel: "GOV.UK｜Standard Visitor",
    officialGuideUrl: "https://www.gov.uk/standard-visitor",
    documentsLabel: "GOV.UK｜支持文件指南",
    documentsUrl: "https://www.gov.uk/government/publications/visitor-visa-guide-to-supporting-documents/guide-to-supporting-documents-visiting-the-uk",
    processingUrl: "https://www.gov.uk/guidance/visa-decision-waiting-times-applications-inside-the-uk",
    feeUrl: "https://www.gov.uk/standard-visitor/apply-standard-visitor-visa",
    requiredDocuments: [doc("护照", "覆盖整个英国停留期"), doc("在线申请信息", "旅行日期、住宿、费用、住址、收入、旅行史等"), doc("资金来源", "银行流水与收入来源能互相解释"), doc("在职/在读或国内情况", "证明真实访客并会离境"), doc("资助人材料", "由他人承担费用时说明关系、金额和资助能力", false), doc("完整翻译件", "非英文或威尔士文材料须可独立核验的完整翻译")],
    applicationSteps: ["确认是否需要 Standard Visitor visa", "在线填表并支付费用", "预约签证中心、录指纹并上传/递交材料", "等待决定，通常为完成身份核验后约 3 周", "收到结果后核对 eVisa 或护照信息"],
    successRate: { status: "not_published", label: "官方未提供可直接套用的中国普通护照个人成功率", url: "https://www.gov.uk/government/statistics/immigration-system-statistics-year-ending-december-2025", note: "不要使用旅行社“通过率”替代官方统计；英国官方材料指南明确不保证成功。" },
    riskTips: ["最常见问题是访问目的、资金来源和回国约束之间无法互相印证", "翻译必须完整并可核验，不能只翻关键句", "Standard Visitor 的长期有效期不等于可长期居住"],
    lastVerified: "2026-08-13"
  },
  AU: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "登录 ImmiAccount 申请",
    applicationUrl: "https://online.immi.gov.au/lusc/login",
    officialGuideLabel: "Home Affairs｜Visitor 600 Tourist stream",
    officialGuideUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600/tourist-stream-overseas",
    documentsLabel: "Home Affairs｜Visitor 600",
    documentsUrl: "https://immi.homeaffairs.gov.au/Visa-subsite/Pages/visit/600-visitor-landing.aspx",
    processingUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-processing-times/global-visa-processing-times",
    feeUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600/tourist-stream-overseas",
    requiredDocuments: [doc("护照与身份证明", "政府签发的身份资料页和旅行历史"), doc("真实访客证据", "旅游目的、工作/家庭/学业和按期离境计划"), doc("资金证明", "支付旅行费用和在澳期间开支的能力"), doc("行程与住宿", "旅游计划、酒店或邀请信息"), doc("英文翻译", "非英文材料按 Home Affairs 要求翻译"), doc("体检/生物信息", "系统或个案要求时完成", false)],
    applicationSteps: ["确认 Visitor 600 Tourist stream", "创建或登录 ImmiAccount", "在线填写、上传材料并付款", "按通知完成体检或生物信息", "用 ImmiAccount 跟踪决定和补件"],
    successRate: { status: "official_context", label: "官方公开访客签证授予数量，但不等同个人成功率", url: "https://www.homeaffairs.gov.au/research-and-statistics/statistics/country-profiles/profiles/peoples-republic-of-china", note: "中国 Visitor grants 可在官方国家概览查看；不同 stream、时期和决定口径不能直接换算个人概率。" },
    riskTips: ["真实访客要用目的、资金和回国约束共同证明", "不要上传无法解释的临时大额资金", "官方 Processing Times Guide 是动态参考，不是出签承诺"],
    lastVerified: "2026-08-13"
  },
  KR: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "进入韩国 Visa Portal 电子申请表",
    applicationUrl: "https://www.visa.go.kr/",
    officialGuideLabel: "韩国驻华使馆｜一般观光 C-3-9",
    officialGuideUrl: "https://overseas.mofa.go.kr/cn-zh/brd/m_1201/view.do?page=1&seq=695439",
    documentsLabel: "所属领区公告与签证中心",
    documentsUrl: "https://overseas.mofa.go.kr/cn-zh/brd/m_1201/list.do",
    processingUrl: "https://overseas.mofa.go.kr/cn-shanghai-zh/brd/m_492/view.do?seq=760835",
    feeUrl: "https://overseas.mofa.go.kr/cn-zh/brd/m_1201/list.do",
    requiredDocuments: [doc("护照与照片", "按韩国签证和领区要求准备"), doc("电子签证申请表", "先核对所属领区是否允许在线填写/预约"), doc("身份证与户籍/居住证明", "按领区清单准备"), doc("在职、在读或收入材料", "证明身份、资金和回国约束"), doc("行程、住宿与返程", "日期和目的保持一致"), doc("领区附加材料", "北京、上海、广州等领区可能不同")],
    applicationSteps: ["按常住地确认领区", "进入 Visa Portal 或领区指定入口", "按清单准备材料并预约签证中心/使领馆", "递交材料与生物信息", "按领区公告查询审理结果"],
    successRate: { status: "not_published", label: "官方未公开可比较的中国普通护照旅游签个人成功率", url: "https://overseas.mofa.go.kr/cn-zh/brd/m_1201/list.do", note: "领区、材料、申请人情况差异大，不能引用中介通过率。" },
    riskTips: ["领区差异是韩国申请的第一风险：上海 C-3-9 审理时间已调整", "不要跨领区只为追求更快排期", "电子申请表、预约和纸质材料必须保持一致"],
    lastVerified: "2026-08-13"
  },
  JP: {
    routeType: "visa", routeLabel: "申请签证 / 指定代理", applicationLabel: "查看日本外务省 eVISA 与指定代理",
    applicationUrl: "https://www.mofa.go.jp/j_info/visit/visa/visaonline.html",
    officialGuideLabel: "日本外务省｜JAPAN eVISA",
    officialGuideUrl: "https://www.mofa.go.jp/j_info/visit/visa/visaonline.html",
    documentsLabel: "日本驻华使馆｜指定代理与申请说明",
    documentsUrl: "https://www.cn.emb-japan.go.jp/itpr_zh/visa_dantai_daili.html",
    processingUrl: "https://www.cn.emb-japan.go.jp/itpr_zh/visa_dantai_daili.html",
    feeUrl: "https://www.cn.emb-japan.go.jp/consular/visa_dantai.htm",
    requiredDocuments: [doc("护照与照片", "按日本签证照片和有效期要求"), doc("签证申请表", "电子签或纸质签按指定代理流程"), doc("行程与住宿", "逐日行程、机票/船票和酒店信息"), doc("资金与职业材料", "在职/在读、收入、银行流水等按类别清单"), doc("代理机构要求材料", "中国境内旅游签通常经指定代理机构递交"), doc("电子签签发通知", "机场联网展示在线签发通知，截图/PDF/打印件不能替代")],
    applicationSteps: ["确认单次、多次或 eVISA 类别", "按居住地查指定代理机构", "准备代理清单并递交", "等待签发通知或领取护照", "使用 eVISA 时在机场在线展示签发通知"],
    successRate: { status: "not_published", label: "官方未公开可比较的中国普通护照旅游签个人成功率", url: "https://www.mofa.go.jp/j_info/visit/visa/visaonline.html", note: "不要把代理机构经验或社交媒体个案当成功率。" },
    riskTips: ["日本 eVISA 的机场展示是在线核验，不是截图展示", "指定代理机构和居住地规则必须按官方最新名单确认", "单次/多次有效期与每次停留期要分开检查"],
    lastVerified: "2026-08-13"
  },
  TH: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "填写泰国 TDAC 入境卡",
    applicationUrl: "https://tdac.immigration.go.th/",
    officialGuideLabel: "泰国外交部｜中泰互免说明",
    officialGuideUrl: "https://www.mfa.go.th/en/content/thcn280124",
    documentsLabel: "泰国移民局｜TDAC 官方指南",
    documentsUrl: "https://tdac.immigration.go.th/manual/cn/index.html",
    processingUrl: "https://tdac.immigration.go.th/manual/cn/index.html",
    feeUrl: "https://tdac.immigration.go.th/manual/cn/index.html",
    requiredDocuments: [doc("中国普通护照", "有效旅行证件"), doc("TDAC 确认信息", "抵达前 3 天内通过官方系统填写"), doc("返程/续程与住宿", "边境可能要求核验"), doc("资金和旅行目的证明", "按个人行程准备"), doc("不能从事的活动说明", "旅游免签不等于工作或长期学习许可")],
    applicationSteps: ["确认中泰互免适用目的", "在抵达前 3 天内填写 TDAC", "保存确认信息", "携带护照、住宿和返程证据入境", "按 30 天单次与 180 天累计规则规划"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；入境仍由边境决定", url: "https://www.mfa.go.th/en/content/thcn280124", note: "不存在“免签包入境”或官方个人通过率。" },
    riskTips: ["TDAC 是入境申报，不是签证，也不收费", "30 天单次与 180 天累计 90 天同时适用", "旅游免签不能替代工作、学习或长期居留许可"],
    lastVerified: "2026-08-13"
  },
  MY: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "填写马来西亚 MDAC",
    applicationUrl: "https://imigresen-online.imi.gov.my/mdac/register",
    officialGuideLabel: "马来西亚移民局｜官方 FAQ",
    officialGuideUrl: "https://malaysiavisa.imi.gov.my/faq/",
    documentsLabel: "马来西亚移民局｜MDAC",
    documentsUrl: "https://www.imi.gov.my/index.php/en/pengumuman/malaysia-digital-arrival-card-mdac/",
    processingUrl: "https://malaysiavisa.imi.gov.my/faq/",
    feeUrl: "https://malaysiavisa.imi.gov.my/faq/",
    requiredDocuments: [doc("有效中国普通护照", "普通或公务普通护照按官方 FAQ"), doc("MDAC 确认信息", "按官方开放窗口提交，核对姓名和护照号"), doc("返程/续程机票", "可能在值机或入境时要求"), doc("住宿和资金", "与停留天数和旅行目的匹配"), doc("明确旅行目的", "免签社会访问不能用于工作或留学")],
    applicationSteps: ["确认 30 天免签和 90/180 累计规则", "按官方窗口填写 MDAC", "保存确认页", "携带护照、住宿、返程和资金材料入境", "不从事工作或留学活动"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；实际停留由入境许可决定", url: "https://malaysiavisa.imi.gov.my/faq/", note: "免签不保证获得完整 30 天。" },
    riskTips: ["MDAC 只用马来西亚移民局官方域名，警惕收费仿冒站", "90/180 是累计口径，不是每次离境就自动重置", "免签社会访问不能替代工作或留学许可"],
    lastVerified: "2026-08-13"
  },
  SG: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "填写 SG Arrival Card",
    applicationUrl: "https://eservices.ica.gov.sg/sgarrivalcard/",
    officialGuideLabel: "新加坡 ICA｜中新互免说明",
    officialGuideUrl: "https://www.ica.gov.sg/news-and-publications/newsroom/media-release/mutual-30-day-visa-exemption-arrangement-between-singapore-and-the-people-s-republic-of-china",
    documentsLabel: "新加坡 ICA｜入境与 SG Arrival Card",
    documentsUrl: "https://www.ica.gov.sg/enter-transit-depart/entering-singapore/sg-arrival-card",
    processingUrl: "https://www.ica.gov.sg/enter-transit-depart/entering-singapore",
    feeUrl: "https://www.ica.gov.sg/enter-transit-depart/entering-singapore/sg-arrival-card",
    requiredDocuments: [doc("有效中国普通护照", "有效期和旅行目的符合入境要求"), doc("SG Arrival Card 提交记录", "抵达前 3 天内通过 ICA 官方系统提交"), doc("返程/续程机票", "按入境官员或承运人要求准备"), doc("住宿、资金和旅行目的", "与停留天数相符"), doc("入境许可", "实际准许停留天数以入境许可为准")],
    applicationSteps: ["确认免签但不保证 30 天", "抵达前 3 天内提交 SG Arrival Card", "保存提交确认", "携带护照和行程材料入境", "检查电子入境许可给出的实际停留期限"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；停留期限由入境许可决定", url: "https://www.ica.gov.sg/enter-transit-depart/entering-singapore", note: "新加坡 ICA 明确免签不等于保证获得 30 天。" },
    riskTips: ["SG Arrival Card 免费，ICA 官方系统是唯一入口", "不要把互免 30 天写成必然停留 30 天", "工作、学习或长期居留要另查对应许可"],
    lastVerified: "2026-08-13"
  },
  FR: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "进入 France-Visas 申请",
    applicationUrl: "https://france-visas.gouv.fr/en/",
    officialGuideLabel: "France-Visas｜中国申请说明",
    officialGuideUrl: "https://www.france-visas.gouv.fr/en/chine",
    documentsLabel: "France-Visas｜短期旅游材料",
    documentsUrl: "https://france-visas.gouv.fr/en/sejour-touristique-de-moins-de-3-mois",
    processingUrl: "https://france-visas.gouv.fr/en/web/france-visas/visa-de-court-sejour",
    feeUrl: "https://france-visas.gouv.fr/en/fees",
    requiredDocuments: commonVisaDocs.concat([doc("申根医疗保险", "覆盖整个申根行程和规定医疗保障"), doc("领区材料", "中国大陆通常按居住地经官方指定中心递交")]),
    applicationSteps: ["用 France-Visas 向导判断类别和材料", "在线填表并生成申请材料清单", "按居住地进入指定 TLScontact 渠道预约", "递交材料、指纹和费用", "等待决定并检查签证页"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的中国普通护照个人成功率", url: "https://france-visas.gouv.fr/en/chine", note: "法国官网公布规则和材料，不提供个人获签保证。" },
    riskTips: ["法国不是“预约快就能申请”的目的地，必须符合主要目的地规则", "申根 90/180 是全区累计，不是法国单国额度", "快速审理参考不等于固定出签承诺"],
    lastVerified: "2026-08-13"
  },
  DE: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "先查德国外交部，再进入 VFS 预约",
    applicationUrl: "https://china.diplo.de/cn-zh/service/visa-einreise",
    officialGuideLabel: "德国外交部｜签证与入境",
    officialGuideUrl: "https://china.diplo.de/cn-zh/service/visa-einreise",
    documentsLabel: "德国外交部｜申根旅游材料",
    documentsUrl: "https://china.diplo.de/cn-de/service/visa-einreise/2703288-2703288",
    processingUrl: "https://china.diplo.de/cn-zh/service/visa-einreise",
    feeUrl: "https://china.diplo.de/cn-de/service/visa-einreise/2703288-2703288",
    requiredDocuments: commonVisaDocs.concat([doc("申根保险", "覆盖所有旅行日期和申根区域"), doc("VIDEX/申请表", "按德国官方表格要求填写并签名"), doc("所属领区证明", "按常住地对应使领馆和 VFS 受理范围")]),
    applicationSteps: ["确认德国为唯一或主要目的地", "在德国外交部页面查所属领区和清单", "按官方链接进入 VFS 预约", "准备原件、复印件、指纹和费用", "等待决定并检查签证页"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的中国普通护照个人成功率", url: "https://china.diplo.de/cn-zh/service/visa-einreise", note: "VFS 是服务商，不应把服务商营销数据当官方成功率。" },
    riskTips: ["德国官方页面和 VFS 受理范围要一起看", "不得用假行程制造“德国主目的地”", "申根签证费与 VFS 服务费分开核对"],
    lastVerified: "2026-08-13"
  },
  IT: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "查看意大利使馆签证表格与领区",
    applicationUrl: "https://ambpechino.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/",
    officialGuideLabel: "意大利外交部｜入境签证",
    officialGuideUrl: "https://www.esteri.it/en/servizi-opportunita/ingressosoggiornoinitalia/visto_ingresso/",
    documentsLabel: "意大利驻华使馆｜表格与材料",
    documentsUrl: "https://ambpechino.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/modelli-e-modulistica/",
    processingUrl: "https://ambpechino.esteri.it/en/servizi-consolari-e-visti/",
    feeUrl: "https://ambpechino.esteri.it/wp-content/uploads/2026/04/ITALY-VISA-FEES-I-QUARTER-TBR-da-1-aprile-2026-colour.pdf",
    requiredDocuments: commonVisaDocs.concat([doc("申根医疗保险", "覆盖全程和申根区"), doc("意大利领区材料", "按居住地和使领馆指定中心清单准备")]),
    applicationSteps: ["判断意大利是否为唯一或主要目的地", "查看意大利驻华使馆对应领区", "下载官方表格和材料清单", "按指定中心预约并递交", "等待决定并核对有效期/次数/停留期"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的中国普通护照个人成功率", url: "https://www.esteri.it/en/servizi-opportunita/ingressosoggiornoinitalia/visto_ingresso/", note: "不要引用旅行社宣传的通过率。" },
    riskTips: ["费率按领区和季度更新，必须打开官方 PDF 核对", "材料翻译和递交渠道由领区决定", "主要目的地规则比预约速度更重要"],
    lastVerified: "2026-08-13"
  },
  ES: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "进入西班牙 BLS 官方预约",
    applicationUrl: "https://spain.blscn.cn/CHN/home/index",
    officialGuideLabel: "西班牙驻华使领馆｜申根签证",
    officialGuideUrl: "https://www.exteriores.gob.es/Consulados/pekin/en/ServiciosConsulares/Paginas/Consular/Visados-Schengen.aspx",
    documentsLabel: "西班牙官方｜申请材料与递交地点",
    documentsUrl: "https://www.exteriores.gob.es/Consulados/pekin/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=China&scd=225&scs=Lugar+de+presentaci%C3%B3n+de+solicitudes+de+visado",
    processingUrl: "https://www.exteriores.gob.es/Consulados/pekin/en/ServiciosConsulares/Paginas/Consular/Visados-Schengen.aspx",
    feeUrl: "https://www.exteriores.gob.es/Consulados/pekin/en/ServiciosConsulares/Paginas/Consular/Visados-Schengen.aspx",
    requiredDocuments: [doc("申根申请表与照片", "每人完整填写、签名并准备近期照片"), doc("护照", "离开申根后通常至少 3 个月有效、至少 2 页空白"), doc("申根保险", "医疗保障至少 €30,000"), doc("住宿、交通和行程", "证明西班牙为唯一或主要目的地"), doc("资金与回国约束", "银行、工作/在读及户籍/居住材料"), doc("领区证明", "按常住地对应 BLS/使领馆")],
    applicationSteps: ["判断西班牙是否为主要目的地", "按居住地进入使领馆指向的 BLS", "填写申请表并预约", "递交材料、指纹和费用", "用官方状态入口跟进结果"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的中国普通护照个人成功率", url: "https://www.exteriores.gob.es/Consulados/pekin/en/ServiciosConsulares/Paginas/Consular/Visados-Schengen.aspx", note: "西班牙官方页面只说明规则、材料和法定时限。" },
    riskTips: ["西班牙官方明确可因无法证明旅行目的而拒绝入境", "BLS 是受委托服务商，入口必须从领馆页面进入", "15 天是一般法定决定期，个案可到 45 天"],
    lastVerified: "2026-08-13"
  },
  AE: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "无需申请签证；查看阿联酋入境要求",
    applicationUrl: "https://www.mofa.gov.ae/en/Missions/Beijing/Services/Visas",
    officialGuideLabel: "阿联酋驻华使馆｜签证说明",
    officialGuideUrl: "https://www.mofa.gov.ae/en/Missions/Beijing/Services/Visas",
    documentsLabel: "阿联酋驻上海总领馆｜签证说明",
    documentsUrl: "https://www.mofa.gov.ae/en/Missions/Shanghai/Services/Visas",
    processingUrl: "https://www.mofa.gov.ae/en/Missions/Beijing/Services/Visas",
    feeUrl: "https://www.mofa.gov.ae/en/Missions/Beijing/Services/Visas",
    requiredDocuments: [doc("有效中国普通护照", "按阿联酋使领馆和承运人要求"), doc("返程/续程机票", "建议随身备查"), doc("酒店/住宿信息", "与访问目的和天数一致"), doc("资金和旅行目的证明", "边境可要求说明"), doc("工作或留学许可", "如目的不是旅游/短期访问，不能用免签替代", false)],
    applicationSteps: ["确认免签适用护照和短期目的", "出发前查阿联酋使领馆和承运人要求", "准备护照、返程、住宿和资金材料", "入境时接受边检并确认停留期限", "需要工作、学习或居留时另办许可"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；实际停留由入境许可决定", url: "https://www.mofa.gov.ae/en/Missions/Beijing/Services/Visas", note: "不要把免签写成保证入境。" },
    riskTips: ["免签不是无限停留，也不是工作/留学许可", "中国普通护照赴阿联酋的政策生效日期不要与反方向混淆", "最终准入由承运人和边境机关决定"],
    lastVerified: "2026-08-13"
  },
  ID: {
    routeType: "evisa", routeLabel: "电子签 / 落地签", applicationLabel: "进入印度尼西亚官方 eVisa",
    applicationUrl: "https://evisa.imigrasi.go.id/",
    officialGuideLabel: "印度尼西亚移民局｜B1 Visa on Arrival",
    officialGuideUrl: "https://jakartapusat.imigrasi.go.id/index.php/layanan/warga-negara-asing-wna/visa-republik-indonesia/b1-visa-saat-kedatangan-wisata",
    documentsLabel: "印度尼西亚移民局｜签证类别",
    documentsUrl: "https://kanwilsultra.imigrasi.go.id/wna/daftar-subjek-voa-bvk-calling-visa",
    processingUrl: "https://evisa.imigrasi.go.id/",
    feeUrl: "https://jakartapusat.imigrasi.go.id/index.php/layanan/warga-negara-asing-wna/visa-republik-indonesia/b1-visa-saat-kedatangan-wisata",
    requiredDocuments: [doc("护照", "按印度尼西亚移民局的有效期和空白页要求"), doc("返程或续程机票", "入境可能核验"), doc("住宿与旅行目的", "酒店、行程或邀请信息"), doc("电子签/落地签付款与确认", "只通过官方 eVisa 或入境口岸办理"), doc("All Indonesia 入境申报", "按当期官方系统要求填写")],
    applicationSteps: ["确认 B1 旅游签、e-VOA 或其他类别", "使用官方 eVisa 系统在线申请，或按规定抵达办理", "准备护照、返程、住宿和付款证明", "按官方要求完成 All Indonesia 入境申报", "入境后检查签证期限和可否延期"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的个人成功率", url: "https://evisa.imigrasi.go.id/", note: "电子签/落地签是资格和材料审核，不是保证签发。" },
    riskTips: ["只认 evisa.imigrasi.go.id，搜索广告仿冒站常收额外费用", "B1 通常有明确停留与延期规则，不能自行延长", "All Indonesia 与签证是两个不同步骤"],
    lastVerified: "2026-08-13"
  },
  VN: {
    routeType: "evisa", routeLabel: "电子签", applicationLabel: "进入越南官方 eVisa",
    applicationUrl: "https://evisa.gov.vn/",
    officialGuideLabel: "越南移民局｜电子签官方入口",
    officialGuideUrl: "https://evisa.gov.vn/",
    documentsLabel: "越南电子签申请系统",
    documentsUrl: "https://evisa.gov.vn/",
    processingUrl: "https://evisa.gov.vn/",
    feeUrl: "https://evisa.gov.vn/",
    requiredDocuments: [doc("护照资料页", "清晰、完整且与申请信息一致"), doc("证件照片", "按系统要求上传"), doc("入境口岸与行程", "填写可使用电子签的口岸和预计日期"), doc("在线支付方式", "单次/多次费用以官方系统支付页为准"), doc("电子签批准文件", "获批后保存并按要求打印或出示")],
    applicationSteps: ["进入 evisa.gov.vn 注册/填写", "上传护照和照片，选择入境口岸", "在线支付并保存申请代码", "按系统查询批准结果", "下载电子签并核对姓名、护照号、日期和口岸"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的个人电子签成功率", url: "https://evisa.gov.vn/", note: "不要用中介“出签率”替代官方系统结果。" },
    riskTips: ["越南 eVisa 费用按官方支付页为准，拒签/错误信息可能不退", "护照号、出生日期和口岸错误会影响使用", "电子签批准不等于边境无条件放行"],
    lastVerified: "2026-08-13"
  },
  NZ: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "进入 Immigration New Zealand Visitor Visa",
    applicationUrl: "https://www.immigration.govt.nz/visas/visitor-visa/",
    officialGuideLabel: "Immigration New Zealand｜Visitor Visa",
    officialGuideUrl: "https://www.immigration.govt.nz/visas/visitor-visa/",
    documentsLabel: "INZ｜中国公民 Visitor Visa 申请指南",
    documentsUrl: "https://www.immigration.govt.nz/process-to-apply/applying-for-a-visa/providing-evidence-and-documents-to-support-your-visa-application/visitor-visa-application-guide-for-citizens-of-china/",
    processingUrl: "https://www.immigration.govt.nz/visas/visitor-visa/",
    feeUrl: "https://www.immigration.govt.nz/visas/visitor-visa/",
    requiredDocuments: [doc("护照与照片", "按 INZ 资料要求上传"), doc("真实访客证据", "访问目的、资金和按期离境安排"), doc("资金/住宿/返程", "证明旅行期间能够自我支持"), doc("英文翻译件", "非英文材料按 INZ 翻译要求"), doc("体检或无犯罪材料", "系统或个案要求时提交", false)],
    applicationSteps: ["判断普通 Visitor Visa 还是 NZeTA 试点", "使用 INZ 在线系统申请 Visitor Visa", "按动态表单上传材料并支付费用", "按通知完成体检/补件", "查看在线账户和决定"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的中国普通护照个人成功率", url: "https://www.immigration.govt.nz/visas/visitor-visa/", note: "官方提供处理时间和规则，不提供个人获签保证。" },
    riskTips: ["普通 Visitor Visa 与持澳签从澳洲出发的 NZeTA 试点不能混为一谈", "在线动态表单只会要求与申请相关的证据，按系统清单递交", "Visitor Visa 处理时间会变化，不要按固定天数承诺"],
    lastVerified: "2026-08-13"
  },
  CA: {
    routeType: "visa", routeLabel: "申请签证", applicationLabel: "进入 IRCC Visitor Visa 申请",
    applicationUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html",
    officialGuideLabel: "加拿大 IRCC｜Visitor Visa",
    officialGuideUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/visitor-visa.html",
    documentsLabel: "加拿大 IRCC｜申请与材料",
    documentsUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html",
    processingUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html",
    feeUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/visitor-visa.html",
    requiredDocuments: [doc("护照", "资料页和旅行历史"), doc("在线申请表与家庭信息", "按 IRCC 账户清单填写"), doc("资金和行程", "说明访问目的、住宿和支付能力"), doc("回国约束", "工作、家庭、资产或其他返程证据"), doc("生物识别", "按 IRCC 通知预约并缴费"), doc("邀请/资助材料", "适用时提交关系和资助能力")],
    applicationSteps: ["在 IRCC 页面确认 Visitor Visa 资格", "使用官方账户创建申请", "按个性化清单上传文件并付款", "按通知完成生物识别", "在线跟踪补件、决定和护照提交"],
    successRate: { status: "not_published", label: "官方未公开可直接套用的中国普通护照个人成功率", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/visitor-visa.html", note: "不要使用签证中介的成功率宣传。" },
    riskTips: ["加拿大 Visitor Visa 的政策生效日期不能借用其他国家或其他国籍 eTA 政策", "IRCC 个性化清单优先于泛化材料表", "生物识别和护照返还时间要计入计划"],
    lastVerified: "2026-08-13"
  },
  TR: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "无需申请签证；查看土耳其外交部国别表",
    applicationUrl: "https://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
    officialGuideLabel: "土耳其外交部｜外国人签证制度",
    officialGuideUrl: "https://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
    documentsLabel: "土耳其外交部｜一般签证信息",
    documentsUrl: "https://www.mfa.gov.tr/general-information-about-turkish-visas.en.mfa",
    processingUrl: "https://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
    feeUrl: "https://www.mfa.gov.tr/general-information-about-turkish-visas.en.mfa",
    requiredDocuments: [doc("有效中国普通护照", "按土耳其外交部国别表"), doc("返程/续程机票", "承运人或边境可能核验"), doc("住宿和行程", "与停留期限一致"), doc("资金与旅行目的", "免签不代表无条件入境"), doc("其他目的签证", "工作、学习或居留不得使用旅游免签", false)],
    applicationSteps: ["查看土耳其外交部国别表", "确认 90/180 口径和旅行目的", "准备护照、返程、住宿和资金材料", "出发前重新检查承运人要求", "入境时接受边境审核"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；入境由边境决定", url: "https://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa", note: "不要把免签写成保证入境。" },
    riskTips: ["90/180 是连续滚动口径，要自己保守核算", "免签旅游不能用于工作、学习或居留", "土耳其外交部国别表是主来源，旅行社宣传不能替代"],
    lastVerified: "2026-08-13"
  },
  GE: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "无需申请签证；查看格鲁吉亚外交部",
    applicationUrl: "https://china.mfa.gov.ge/important-information",
    officialGuideLabel: "格鲁吉亚外交部｜互免生效",
    officialGuideUrl: "https://mfa.gov.ge/en/news/425297-28-misidan-saqartvelosa-da-chinetis-sakhalkho-respublikas-shoris-uvizo-mimosvlis-shesakheb-shetankhm",
    documentsLabel: "格鲁吉亚驻华使馆｜重要信息",
    documentsUrl: "https://china.mfa.gov.ge/important-information",
    processingUrl: "https://china.mfa.gov.ge/important-information",
    feeUrl: "https://china.mfa.gov.ge/important-information",
    requiredDocuments: [doc("有效中国普通护照", "按互免协议和使馆说明"), doc("返程/续程与住宿", "边境可能要求"), doc("资金与保险", "建议随身准备可核验证据"), doc("真实旅行目的", "工作、学习等活动需另办许可"), doc("口岸与第三国过境材料", "途经其他国家要另查规则", false)],
    applicationSteps: ["确认旅游免签和 30/90/180 规则", "准备护照、返程、住宿、资金和保险", "核对国际口岸与过境国家要求", "入境时说明真实目的和停留天数", "保守记录累计停留"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；实际准入由边境决定", url: "https://china.mfa.gov.ge/important-information", note: "免签不等于无条件入境。" },
    riskTips: ["30 天单次与 90/180 累计同时满足", "不要以频繁出入境代替居留许可", "格鲁吉亚与第三国转机/陆路过境需分别核验"],
    lastVerified: "2026-08-13"
  },
  RU: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "无需申请签证；查看俄方免签公告",
    applicationUrl: "https://ru.china-embassy.gov.cn/lsfw/zytz_142816/202607/t20260721_11989093.htm",
    officialGuideLabel: "中国驻俄使馆｜免签说明",
    officialGuideUrl: "https://ru.china-embassy.gov.cn/lsfw/zytz_142816/202607/t20260721_11989093.htm",
    documentsLabel: "中国驻哈巴罗夫斯克总领馆｜适用范围",
    documentsUrl: "https://khabarovsk.china-consulate.gov.cn/lsfw/ZYTZ/202512/t20251202_11764651.htm",
    processingUrl: "https://ru.china-embassy.gov.cn/lsfw/zytz_142816/202607/t20260721_11989093.htm",
    feeUrl: "https://ru.china-embassy.gov.cn/lsfw/zytz_142816/202607/t20260721_11989093.htm",
    backupRouteLabel: "核对俄罗斯电子签允许用途",
    backupRouteUrl: "https://electronic-visa.kdmid.ru/faq_en.html",
    requiredDocuments: [doc("有效中国普通护照", "适用临时免签公告的普通护照"), doc("返程/续程与住宿", "入境和移民登记可能核验"), doc("资金与旅行目的", "与旅游、探亲、商务等公告列明目的一致"), doc("移民登记凭证", "按住宿地要求完成并保存"), doc("相应签证", "工作、采访、学习、居留等不适用免签", false)],
    applicationSteps: ["确认短期目的属于免签公告范围", "核对现行期限至 2027-12-31", "准备护照、行程、住宿、返程和资金证据", "抵达后按住宿地要求办理移民登记", "不适用免签目的时改查相应签证/电子签"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；边境机关作最终决定", url: "https://ru.china-embassy.gov.cn/lsfw/zytz_142816/202607/t20260721_11989093.htm", note: "电子签备用通道也不构成准入保证。" },
    riskTips: ["俄罗斯现行免签已延长至 2027-12-31，但仍是临时政策，应每周复核", "工作、新闻采访、学习、居留等目的不能使用免签", "电子签须先核对允许用途；工作、学习、居留须办理相应签证"],
    lastVerified: "2026-08-13"
  },
  PH: {
    routeType: "visa_free", routeLabel: "限时免签入境", applicationLabel: "填写菲律宾 eTravel 入境申报",
    applicationUrl: "https://etravel.gov.ph/",
    officialGuideLabel: "菲律宾 eVisaPH｜中国公民免签政策",
    officialGuideUrl: "https://evisa.gov.ph/page/policy?l1=Non-Immigrant+Visas",
    documentsLabel: "中国驻菲律宾使馆｜14 天免签提醒",
    documentsUrl: "https://ph.china-embassy.gov.cn/chn/lsfw/202601/t20260122_11843596.htm",
    processingUrl: "https://evisa.gov.ph/page/policy?l1=Non-Immigrant+Visas",
    feeUrl: "https://evisa.gov.ph/page/policy?l1=Non-Immigrant+Visas",
    backupRouteLabel: "停留超过 14 天：查看菲律宾 eVisa",
    backupRouteUrl: "https://evisa.gov.ph/",
    requiredDocuments: [doc("有效中国普通护照", "拟停留期后至少 6 个月有效，并有空白页"), doc("往返或续程机票", "菲律宾使领馆和边检可能核验"), doc("确认酒店订单", "覆盖计划停留日期"), doc("菲律宾行程与必要证明", "与旅游或商务目的相符"), doc("eTravel QR 信息", "抵达前 72 小时内通过官方系统免费登记"), doc("其他入境签证", "转机赴第三国、工作、学习或超过 14 天时另查", false)],
    applicationSteps: ["确认只做旅游或商务短期访问", "确认从 NAIA 或 MCIA 入境且停留不超过 14 天", "抵达前 72 小时内填写菲律宾 eTravel", "准备护照、酒店、返程/续程机票和行程证明", "超过 14 天或其他目的改查 eVisa/相应签证"],
    successRate: { status: "not_applicable", label: "免签没有签证成功率；菲律宾边检作最终决定", url: "https://evisa.gov.ph/page/policy?l1=Non-Immigrant+Visas", note: "14 天免签不可延期、不可转换为其他签证类别。" },
    riskTips: ["只允许从马尼拉 NAIA 或宿务 MCIA 入境", "转机赴第三国不适用该免签安排", "eTravel 免费，收费登记站不是官方入口"],
    lastVerified: "2026-08-13"
  },
  KH: {
    routeType: "visa_free", routeLabel: "限时免签入境", applicationLabel: "填写柬埔寨 e-Arrival 入境卡",
    applicationUrl: "https://www.arrival.gov.kh/",
    officialGuideLabel: "中国驻柬埔寨使馆｜限时免签提醒",
    officialGuideUrl: "https://kh.china-embassy.gov.cn/lsfws/lsbh/202606/t20260620_11949230.htm",
    documentsLabel: "柬埔寨 e-Arrival 官方入口",
    documentsUrl: "https://www.arrival.gov.kh/",
    processingUrl: "https://www.arrival.gov.kh/",
    feeUrl: "https://www.evisa.gov.kh/",
    backupRouteLabel: "免签结束或不适用：查看柬埔寨 e-Visa",
    backupRouteUrl: "https://www.evisa.gov.kh/",
    requiredDocuments: [doc("中国普通护照", "免签期间适用中华人民共和国普通护照"), doc("e-Arrival 电子入境卡", "抵达前 7 天内可填，也可抵达现场办理"), doc("返程/续程与住宿", "入境可能核验"), doc("短期旅游行程", "限时免签只按短期旅游口径准备"), doc("免签期限核对", "2026-06-15 至 2026-10-15，单次不超过 14 天"), doc("签证", "免签结束、停留超过 14 天或目的不适用时办理", false)],
    applicationSteps: ["确认出发日期落在 2026-06-15 至 10-15 免签期内", "确认每次停留不超过 14 天且为短期旅游", "抵达前 7 天内通过 arrival.gov.kh 填写 e-Arrival", "保存电子入境卡与护照、住宿、返程材料", "免签期外改查官方 e-Visa 或其他签证"],
    successRate: { status: "not_applicable", label: "免签没有签证成功率；入境由柬埔寨边检决定", url: "https://kh.china-embassy.gov.cn/lsfws/lsbh/202606/t20260620_11949230.htm", note: "这是限时政策，不代表长期免签制度。" },
    riskTips: ["限时免签将于 2026-10-15 结束，不能当作长期规则", "单次停留不超过 14 天，免签本身不能延期", "e-Arrival 只认 arrival.gov.kh，警惕收费仿冒站"],
    lastVerified: "2026-08-13"
  },
  BR: {
    routeType: "visa_free", routeLabel: "限时免签入境", applicationLabel: "查看巴西官方免签与入境说明",
    applicationUrl: "https://www.gov.br/mre/pt-br/consulado-cantao/EN/visas/info",
    officialGuideLabel: "巴西外交部驻广州总领馆｜签证与免签",
    officialGuideUrl: "https://www.gov.br/mre/pt-br/consulado-cantao/EN/visas/info",
    documentsLabel: "巴西外交部｜换文与实施依据",
    documentsUrl: "https://aplicacao.itamaraty.gov.br/ApiConcordia/Documento/download/34167",
    processingUrl: "https://www.gov.br/mre/pt-br/consulado-cantao/EN/visas/info",
    feeUrl: "https://www.gov.br/mre/pt-br/consulado-cantao/EN/visas/info",
    backupRouteLabel: "超过免签范围：进入巴西 VFS 申请入口",
    backupRouteUrl: "https://visa.vfsglobal.com/chn/en/bra/apply-visa",
    requiredDocuments: [doc("有效中国普通护照", "中国普通护照，按承运人和巴西边检要求准备"), doc("返程或续程机票", "旅游、商务或过境行程的离境证明"), doc("住宿/会议/活动材料", "与旅游、商务、过境或艺术体育目的相符"), doc("30 天累计规划", "自首次入境日起连续 12 个月的 migration year 累计不超过 30 天"), doc("入境健康与边检材料", "按承运人和巴西边检当期要求准备"), doc("相应签证", "工作、学习、其他目的或超过累计上限时办理", false)],
    applicationSteps: ["确认目的属于旅游、商务、过境或艺术体育活动", "确认 2026-05-11 至 12-31 的限时免签适用", "按首次入境日起的 migration year 记录累计天数", "准备护照、返程/续程、住宿或活动证明", "工作、学习、其他目的或超过 30 天改走 VFS 签证流程"],
    successRate: { status: "not_applicable", label: "免签没有签证成功率；巴西边检作最终决定", url: "https://www.gov.br/mre/pt-br/consulado-cantao/EN/visas/info", note: "免签有效至 2026-12-31，且不可延期。" },
    riskTips: ["30 天是每个 migration year 累计上限，不是每个自然年", "工作、学习等目的不在此次免签范围内", "限时政策到期前要重新核对巴西外交部页面"],
    lastVerified: "2026-08-13"
  },
  KZ: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "查看哈萨克斯坦入境与申报要求",
    applicationUrl: "https://www.gov.kz/situations/497/1149?lang=en",
    officialGuideLabel: "中国外交部｜中哈互免签证协定",
    officialGuideUrl: "https://www.mfa.gov.cn/wjbzwfwpt/kzx/tzgg/202311/t20231103_11172619.html",
    documentsLabel: "哈萨克斯坦政府｜外国人到达申报",
    documentsUrl: "https://www.gov.kz/situations/497/1149?lang=en",
    processingUrl: "https://cs.mfa.gov.cn/zggmcg/ljmdd/yz_645708/hskst_646454/",
    feeUrl: "https://www.gov.kz/memleket/entities/mfa/activities/34747?lang=en&parentId=3053",
    backupRouteLabel: "超出免签目的或期限：查看哈萨克斯坦签证规则",
    backupRouteUrl: "https://www.gov.kz/memleket/entities/mfa/activities/34747?lang=en&parentId=3053",
    requiredDocuments: [doc("有效中国普通护照", "按中哈协定适用旅行证件和边境要求准备"), doc("返程/续程机票", "边境可能核验离境安排"), doc("住宿地址", "酒店、民宿或私人接待地址应真实可核验"), doc("接待方到达申报", "接待方通常须在抵达后 3 个工作日内完成通知"), doc("旅行目的与资金证明", "与免签目的和停留天数相符"), doc("相应签证", "工作、学习、长期居留或超出协定目的时办理", false)],
    applicationSteps: ["确认普通护照和旅行目的符合中哈免签协定", "按单次 30 天、180 天累计 90 天规划行程", "提前确认酒店或接待方会完成到达申报", "抵达后 3 个工作日内向接待方确认申报已提交", "工作、学习或长期停留改查哈萨克斯坦签证规则"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；实际准入由边境机关决定", url: "https://www.mfa.gov.cn/wjbzwfwpt/kzx/tzgg/202311/t20231103_11172619.html", note: "不要把免签写成保证入境。" },
    riskTips: ["住宿申报由接待方负责，但旅客要主动确认", "哈萨克斯坦不办理落地签，超出免签目的须提前申请", "30 天单次与 180 天累计 90 天同时适用"],
    lastVerified: "2026-08-14"
  },
  UZ: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "查看乌兹别克斯坦入境与住宿登记",
    applicationUrl: "https://my.gov.uz/en/for-foreigners",
    officialGuideLabel: "乌兹别克斯坦外交部｜中乌互免签证协定",
    officialGuideUrl: "https://gov.uz/en/mfa/news/view/53659",
    documentsLabel: "乌兹别克斯坦政府｜外国人登记说明",
    documentsUrl: "https://my.gov.uz/en/for-foreigners",
    processingUrl: "https://cs.mfa.gov.cn/zggmcg/ljmdd/yz_645708/wzbkst_647880/rjjl_647890/",
    feeUrl: "https://gov.uz/en/mfa/pages/o-zbekiston-respublikasi-vizasi",
    backupRouteLabel: "超过 30 天或不适用免签：进入乌兹别克斯坦 e-Visa",
    backupRouteUrl: "https://e-visa.gov.uz/",
    requiredDocuments: [doc("有效中国普通护照", "官方外国人页面提示护照应留足 6 个月有效期"), doc("返程/续程机票", "用于说明短期访问和离境安排"), doc("住宿登记确认", "酒店通常代办；私人住所需由接待方或本人办理"), doc("行程、住宿和资金", "边境可能要求核验"), doc("旅行目的证明", "免签不覆盖工作、学习、媒体报道等活动"), doc("相应签证或邀请函", "超过 30 天或从事需许可活动时准备", false)],
    applicationSteps: ["确认中乌免签自 2025-06-01 生效", "按单次 30 天、180 天累计 90 天安排", "入住酒店时确认酒店会通过系统登记", "住私人住所时在 3 个工作日内完成登记并保存凭证", "超过 30 天或工作/学习改走官方 e-Visa 或相应签证"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；边境机关作最终决定", url: "https://gov.uz/en/mfa/news/view/53659", note: "住宿登记和免签资格都不保证入境。" },
    riskTips: ["住宿登记凭证要保存到离境", "工作、学习、媒体活动不适用普通旅游免签", "不要把 30 天单次和 90/180 累计混写"],
    lastVerified: "2026-08-14"
  },
  RS: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "查看塞尔维亚入境要求",
    applicationUrl: "https://www.mfa.gov.rs/en/citizens/travel-serbia/general-entry-requirements",
    officialGuideLabel: "塞尔维亚外交部｜中国签证制度",
    officialGuideUrl: "https://www.mfa.gov.rs/en/citizens/travel-abroad/visas-and-states-travel-advisory/china",
    documentsLabel: "塞尔维亚外交部｜一般入境要求",
    documentsUrl: "https://www.mfa.gov.rs/en/citizens/travel-serbia/general-entry-requirements",
    processingUrl: "https://www.srbija.gov.rs/vest/en/120331/agreement-on-abolition-of-visas-between-serbia-china-in-force.php",
    feeUrl: "https://www.mfa.gov.rs/en/citizens/travel-serbia/general-entry-requirements",
    backupRouteLabel: "不适用免签：进入塞尔维亚外国人门户",
    backupRouteUrl: "https://welcometoserbia.gov.rs/",
    requiredDocuments: [doc("有效中国普通护照", "按塞尔维亚外交部国别制度准备"), doc("返程/续程机票", "边境可能要求证明离境安排"), doc("酒店订单或邀请函", "证明旅行目的和住宿地址"), doc("资金证明", "官方一般要求按每天约 50 欧元准备"), doc("医疗保险", "官方建议覆盖至少 20,000 欧元医疗费用"), doc("相应签证", "工作、学习、长期居留或不适用免签时办理", false)],
    applicationSteps: ["确认中国普通护照短期访问适用 30 天免签", "准备返程、住宿、资金和保险证明", "核对是否需要向住宿方完成当地登记", "入境时如实说明目的、停留天数和下一程", "工作、学习或长期停留改查官方外国人门户"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；塞尔维亚边境机关作最终决定", url: "https://www.mfa.gov.rs/en/citizens/travel-serbia/general-entry-requirements", note: "官方可要求出示资金、住宿和返程证明。" },
    riskTips: ["免签 30 天不要与持其他国家签证的 90/180 便利混用", "边境可能要求每天 50 欧元资金证明", "不适用免签时只从 welcometoserbia.gov.rs 查申请路径"],
    lastVerified: "2026-08-14"
  },
  MA: {
    routeType: "visa_free", routeLabel: "免签入境", applicationLabel: "查看摩洛哥入境与领事要求",
    applicationUrl: "https://www.consulat.ma/",
    officialGuideLabel: "中国领事服务网｜摩洛哥入境居留",
    officialGuideUrl: "https://cs.mfa.gov.cn/zggmcg/ljmdd/fz_648564/mlg_650861/rjjl_650871/",
    documentsLabel: "中国领事服务网｜摩洛哥免签细化说明",
    documentsUrl: "https://cs.mfa.gov.cn/zggmcg/ljmdd/fz_648564/mlg_650861/fwxx/201606/t20160607_940983.shtml",
    processingUrl: "https://www.consulat.ma/",
    feeUrl: "https://www.consulat.ma/",
    backupRouteLabel: "超过 90 天或其他目的：查看摩洛哥领事门户",
    backupRouteUrl: "https://www.consulat.ma/",
    requiredDocuments: [doc("有效中国普通护照", "入境时有效期应大于 6 个月"), doc("返程/续程机票", "边检可能要求查看"), doc("酒店订单或邀请函", "中国领事服务网提示可能被查验"), doc("资金与旅行目的证明", "与停留天数和行程一致"), doc("旅行保险", "官方安全提醒建议购买旅行和意外保险"), doc("长期居留/工作许可", "超过 90 天或非旅游目的不能只用免签", false)],
    applicationSteps: ["确认中国护照适用 90 天免签", "准备护照、返程、住宿、资金和行程材料", "从第三国出发时另查转机国家过境规则", "入境时接受摩洛哥边境审查并保存入境记录", "超过 90 天或工作/长期居留改查领事和居留路径"],
    successRate: { status: "not_applicable", label: "免签政策没有签证成功率；实际准入由摩洛哥边境机关决定", url: "https://cs.mfa.gov.cn/zggmcg/ljmdd/fz_648564/mlg_650861/rjjl_650871/", note: "免签不等于只带护照就保证入境。" },
    riskTips: ["护照有效期大于 6 个月是重点条件", "边检可能要求机票、酒店或邀请函", "长期居留需及时办理居留证，不能用免签无限续期"],
    lastVerified: "2026-08-14"
  }
};

export function enrichCountries(countries, extraGuides = {}) {
  return countries.map(country => ({
    ...country,
    application: applicationGuides[country.code] || extraGuides[country.code] || null
  }));
}
